dfflst = {'type': 'root',
             'children': [{'key': 'common',
                           'value': {'type': 'root',
                                     'children': [{'key': 'follow',
                                                   'old_value': 'EMPTY',
                                                   'new_value': False,
                                                   'type': 'leaf',
                                                   'change': 'IN_SECOND'},
                                                  {'key': 'setting1',
                                                   'old_value': 'Value 1',
                                                   'new_value': 'Value 1',
                                                   'type': 'leaf',
                                                   'change': 'SAME'},
                                                  {'key': 'setting2',
                                                   'old_value': 200,
                                                   'new_value': 'EMPTY',
                                                   'type': 'leaf',
                                                   'change': 'IN_FIRST'},
                                                  {'key': 'setting3',
                                                   'old_value': True,
                                                   'new_value': None,
                                                   'type': 'leaf',
                                                   'change': 'CHANGED'},
                                                  {'key': 'setting4',
                                                   'old_value': 'EMPTY',
                                                   'new_value': 'blah blah',
                                                   'type': 'leaf',
                                                   'change': 'IN_SECOND'},
                                                  {'key': 'setting5',
                                                   'old_value': 'EMPTY',
                                                   'new_value': {'key5': 'value5'},
                                                   'type': 'leaf',
                                                   'change': 'IN_SECOND'},
                                                  {'key': 'setting6',
                                                   'value': {'type': 'root',
                                                             'children': [{'key': 'doge',
                                                                           'value': {'type': 'root',
                                                                                     'children': [{'key': 'wow',
                                                                                                   'old_value': '',
                                                                                                   'new_value': 'so '
                                                                                                                'much',
                                                                                                   'type': 'leaf',
                                                                                                   'change': 'CHANGED'}]},
                                                                           'type': 'leaf',
                                                                           'change': 'NESTED'},
                                                                          {'key': 'key',
                                                                           'old_value': 'value',
                                                                           'new_value': 'value',
                                                                           'type': 'leaf',
                                                                           'change': 'SAME'},
                                                                          {'key': 'ops',
                                                                           'old_value': 'EMPTY',
                                                                           'new_value': 'vops',
                                                                           'type': 'leaf',
                                                                           'change': 'IN_SECOND'}]},
                                                   'type': 'leaf',
                                                   'change': 'NESTED'}]},
                           'type': 'leaf',
                           'change': 'NESTED'},
                          {'key': 'group1',
                           'value': {'type': 'root',
                                     'children': [{'key': 'baz',
                                                   'old_value': 'bas',
                                                   'new_value': 'bars',
                                                   'type': 'leaf',
                                                   'change': 'CHANGED'},
                                                  {'key': 'foo',
                                                   'old_value': 'bar',
                                                   'new_value': 'bar',
                                                   'type': 'leaf',
                                                   'change': 'SAME'},
                                                  {'key': 'nest',
                                                   'old_value': {'key': 'value'},
                                                   'new_value': 'str',
                                                   'type': 'leaf',
                                                   'change': 'CHANGED'}]},
                           'type': 'leaf',
                           'change': 'NESTED'},
                          {'key': 'group2',
                           'old_value': {'abc': 12345, 'deep': {'id': 45}},
                           'new_value': 'EMPTY',
                           'type': 'leaf',
                           'change': 'IN_FIRST'},
                          {'key': 'group3',
                           'old_value': 'EMPTY',
                           'new_value': {'deep': {'id': {'number': 45}}, 'fee': 100500},
                           'type': 'leaf',
                           'change': 'IN_SECOND'}]}